### ISSUE TITLE
LEDs fade out unexpectedly

### ISSUE THREAD

**Issue by piebrain** [piebrain/G3-FW#1]
LEDs sometimes fade out to save power immediately after button click in radio mode (they should wait a minute or so before doing this...)

**Comment by NathanV75** [comment]
I am thinking this is resolved as best as possible. I could not find a way for the callback to say whether the it was the timer or button press that woke it up. The best I can do is check for button press right at wakeup (which is being done now).

I haven't noticed this happening since #6.
