### ISSUE TITLE
Power down jingle not played in Radio Mode

### ISSUE THREAD

**Issue by NathanV75** [piebrain/G3-FW#12]
When in radio mode and the power button is pressed the power down jingle is not played. The led animation is still shown.

**Comment by piebrain** [comment]
Inserting this before playing the jingle seems to fix the problem.

`io->digitalWrite(RAD_SD_POW, LOW);
delay(10);
`

@jamesihutton can you explain why?

**Comment by jamesihutton** [comment]
The audio DAC on the board handles any audio output coming from the ESP (so everything but the radio). This obviously includes the jingle. 
In the latest hardware rev, the DAC on the board is on the same power line as the SD card (powered on when this pin is LOW). 
So this power line needed to be activated to turn the DAC on and hear any output from the ESP's I2S line. 
You can change the pin name if you want to update it to reflect "SD and DAC power".

**Comment by jamesihutton** [comment]
I also wait 10ms just to let the line settle before proceeding. (not sure if needed).

**Comment by piebrain** [comment]
Does RAD_SD_POW also control power to the radio?

**Comment by jamesihutton** [comment]
Yes... more or less. It goes to the reset line of the radio. 

So to be clear, when this line is low, the DAC and the SD card are powered and the radio is perpetually held in "reset" (effectively stops any power running through the radio). When this line is high, the DAC and SD card lose power, and the radio is released from reset state.

**Comment by jamesihutton** [comment]
I had to get a little creative for the IO lines since we were running so short on them....
