### ISSUE TITLE
Review and Fix Compile Warnings

### ISSUE THREAD

**Issue by sastel** [piebrain/G3-FW#21]
When I built with vsCode and PlatformIO there were a series of compiler warnings which do not prevent the build from happening but should be addressed in the future. Some of them may cause subtle bugs (especially "variable x may be used uninitialized in this function").
A few of the warnings are in our files, but most of them are in 3rd party libraries.

**Comment by smellystelly** [comment]
`Compiling .pio/build/compass/libc31/ESP8266Audio/AudioOutputSerialWAV.cpp.o
.pio/libdeps/compass/ESP8266Audio/src/AudioOutputSPIFFSWAV.cpp: In member function 'virtual bool AudioOutputSPIFFSWAV::begin()':
.pio/libdeps/compass/ESP8266Audio/src/AudioOutputSPIFFSWAV.cpp:46:3: warning: 'SPIFFS' is deprecated (declared at /home/sstel/.platformio/packages/framework-arduinoespressif8266/cores/esp8266/FS.h:269): SPIFFS has been deprecated. Please consider moving to LittleFS or other filesystems. [-Wdeprecated-declarations]
   SPIFFS.remove(filename);
   ^
.pio/libdeps/compass/ESP8266Audio/src/AudioOutputSPIFFSWAV.cpp:47:7: warning: 'SPIFFS' is deprecated (declared at /home/sstel/.platformio/packages/framework-arduinoespressif8266/cores/esp8266/FS.h:269): SPIFFS has been deprecated. Please consider moving to LittleFS or other filesystems. [-Wdeprecated-declarations]
   f = SPIFFS.open(filename, "w+");
       ^`

**Comment by smellystelly** [comment]
`Compiling .pio/build/compass/lib756/Compass/CompassAudioGeneratorMP3.cpp.o
.pio/libdeps/compass/ESP8266Audio/src/opusfile/opusfile.c: In function 'op_open_seekable2':
.pio/libdeps/compass/ESP8266Audio/src/opusfile/opusfile.c:1253:10: warning: 'end_offset' may be used uninitialized in this function [-Wmaybe-uninitialized]
       ret=op_find_final_pcm_offset(_of,serialnos,nserialnos,
          ^
.pio/libdeps/compass/ESP8266Audio/src/opusfile/opusfile.c:1134:17: note: 'end_offset' was declared here
     ogg_int64_t end_offset;
                 ^
.pio/libdeps/compass/ESP8266Audio/src/opusfile/opusfile.c: In function 'op_pcm_seek':
.pio/libdeps/compass/ESP8266Audio/src/opusfile/opusfile.c:2391:16: warning: 'li' may be used uninitialized in this function [-Wmaybe-uninitialized]
   _of->cur_link=_li;
                ^
.pio/libdeps/compass/ESP8266Audio/src/opusfile/opusfile.c:2592:22: note: 'li' was declared here
   int                li;
                      ^`

**Comment by smellystelly** [comment]
`Compiling .pio/build/compass/FrameworkArduino/Crypto.cpp.o
lib/Compass/Navigation.cpp: In member function 'uint8_t Navigation::left()':
lib/Compass/Navigation.cpp:137:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
lib/Compass/Navigation.cpp: In member function 'void Navigation::updateVP(uint8)':
lib/Compass/Navigation.cpp:231:10: warning: unused variable 'prefix' [-Wunused-variable]
     char prefix;
          ^
lib/Compass/Navigation.cpp:233:13: warning: unused variable 'numberSize' [-Wunused-variable]
     uint8_t numberSize;
             ^
lib/Compass/Navigation.cpp:239:9: warning: unused variable 'i' [-Wunused-variable]
     int i = 0;
         ^
lib/Compass/Navigation.cpp: In member function 'void Navigation::listFolders(uint8_t)':
lib/Compass/Navigation.cpp:167:61: warning: 'numberSize' may be used uninitialized in this function [-Wmaybe-uninitialized]
                 int number = folder.substring(1, numberSize + 1).toInt();
                                                             ^
lib/Compass/Navigation.cpp:166:13: warning: 'prefix' may be used uninitialized in this function [-Wmaybe-uninitialized]
             if (folder[0] == prefix) {
             ^`

**Comment by piebrain** [comment]
The first 2 ones are related to ESP8266Audio.
- SPIFFS is deprecated in Arduino, but still supported in ESP8266Audio.
- We don't use Opus at all, because it is currently not supported on ESP8266

Navigation is not finished yet, so hope @NathanV75 will take care of that.
