### ISSUE TITLE
Huge power loss on player mode

### ISSUE THREAD

**Issue by jamesihutton** [piebrain/G3-FW#37]
The target power consumption for player mode is ~55mA on low volume with the LEDs faded off.
This is achieved when the device boots up directly into player mode.

However, when you go from radio mode to player mode, the device now burns 160mA continuously. 
This seems to be a new bug since porting everything over to the piebrain repo.

Radio mode is not affected (achieves target ~28mA)

**Comment by sastel** [comment]
How much does the radio chip burn when it is switched on?

**Comment by sastel** [comment]
Seems like this would be caused either by:
1. Unused hardware not being switched off while in player mode.
2. Additional CPU usage.
Do we have any hints as to what the cause is?

**Comment by sastel** [comment]
Some additional notes:
Previously transition was handled by main.cpp's switch_mode_track() function.
Now the sequence of events is as follows:

1. FM_RADIO state gets MODE_BTN_EVT (after the SLEEP state ignores it)
2. FM_RADIO requests a transition to PLAYER
3. SLEEP exits
4. FM_RADIO exits (gets EXIT_EVT and commands the radio to power down)
5. PLAYER enters (gets ENTRY_EVT which writes RAD_RST_SD_DAC_POW low... putting the radio into reset... and starts to play tracks)

**Comment by jamesihutton** [comment]
> How much does the radio chip burn when it is switched on?

Around 20mA. 
However, if I remember correctly, the line that turns the SD card and DAC on is the reset line for the radio chip, effectively turning the radio chip off whenever the SD card and DAC are on. 

When the radio chip reset line is low, it is perpetually in "reset" uses no power.

**Comment by sastel** [comment]
This one might be tricky to debug, since I don't have a method of measuring the current usage. How are you measuring it?

**Comment by jamesihutton** [comment]
Yeah, it'll be a mix of hardware and fw on this one. I have to have the device open and using a meter to measure. 
One way you could measure it is take the battery out and power the device with a USB current meter if you have one.

Likely I'll just have to figure out where the power is leaking before ya'll can fix it in FW.

**Comment by piebrain** [comment]
What about WiFi.forceSleepBegin() in wakeup_cb()?

If wifi is turned on for some reason after sleep it could take maybe the extra 100mA.

**Comment by jamesihutton** [comment]
> What about WiFi.forceSleepBegin() in wakeup_cb()?
> 
> If wifi is turned on for some reason after sleep it could take maybe the extra 100mA.

That's definitely a possibility. WiFi does use around that much power when it's on.

**Comment by sastel** [comment]
@jamesihutton can you check if the current consumption jumps up when in radio mode after the first wakeup from sleep? The WiFi.forceSleepBegin() function is not being called after wakeup, which would explain the problem.
Also can you checkout branch ```bugfix/ss/issue-37-huge-power-loss-on-player-mode``` in git, build and load to the device, and see if my change fixes the problem?

**Comment by jamesihutton** [comment]
Yep, I'll do that Monday or Tuesday. Thanks!

**Comment by jamesihutton** [comment]
bugfix/ss/issue-37-huge-power-loss-on-player-mode did not fix the bug. 

I ran some power tests and located the power loss. 
It's all being consumed by the ESP chip - so you're on the right track... it's definitely something to do with the WiFi or state of the ESP.

**Comment by jamesihutton** [comment]
Adding "WiFi.forceSleepBegin()" in "void init_track()" in "main.cpp" solves the power issue. 

Obviously I don't know if this is the best place to put this line or how to handle this properly... so I'll leave the final fix to you @sastel

**Comment by sastel** [comment]
@jamesihutton which commit is init_track() in? I haven't been able to find it.

**Comment by jamesihutton** [comment]
G3-FW uses functions in G3-ESP no?
I added "WiFi.forceSleepBegin()" in the "init_track()" function in  "G3-FW/G3-ESP\src\main.cpp" line ~165

**Comment by piebrain** [comment]
https://github.com/piebrain/G3-FW is the repo we are currently using. It has no G3-ESP directory. I believe you are referring to your original repo at https://github.com/jamesihutton/G3_FW

**Comment by jamesihutton** [comment]
Your right, I had both repos opened and was pulling from the wrong one. 
Sorry I've been out of the FW for too long now!
Your original bug fix works :)
