### ISSUE TITLE
Reset SD In Power Up Sequence

### ISSUE THREAD

**Issue by sastel** [piebrain/G3-FW#66]
The SD card does need to be reset on power up so that the device can read JSON settings from the SD card.
This might be the time to add an "init" state.

**Comment by sastel** [comment]
Rethinking some states in the HSM here.
Currently I have a clunky "on" state that includes everything except the off state. The off state is just an intermediate state where the device unlatches power so that if unplugged it will turn off.
The "on" state has a task running which monitors battery level and generates the BATTERY_OUT_EVT (for battery level "low low") and BATTERY_LOW_EVT (for battery level low).
Currently the battery level events can be generated for charging and usbdrive modes. This doesn't make sense since in these modes the device is plugged in and charging. (It would be annoying to have the "battery low" warning keep happening even after the device is plugged in, but this design makes the problem possible) It might be useful to introduce a "plugged" state.
The "on" state won't need to exist if I redesign carefully.

**Comment by sastel** [comment]
Actually a "plugged" state wouldn't make sense either, because the HSM may be in the "running" state when plugged or unplugged.

**Comment by piebrain** [comment]
@sastel could we fix this bug now and rethink the states later?

**Comment by sastel** [comment]
@piebrain yes I can. It will involve some minor changes to the state machine though.
